services:
  tracking_server:
    image: ghcr.io/mlflow/mlflow:latest
    restart: always
    command: mlflow server --default-artifact-root /mlflow --host 0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlflow:/mlflow

  mlops_practice:
    build: .
    depends_on:
      - tracking_server
    volumes:
      - ./data:/app/data
